name: App check
on: push
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.3'
      - name: Get dependencies
        run: flutter pub get
      - name: Format check
        run: dart format --output=none --set-exit-if-changed .

  lint-check:
    needs: format-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.3'
      - name: Get dependencies
        run: flutter pub get
      - name: Lint check
        run: flutter analyze

  build-apk:
    needs: lint-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.3'
      - name: Get dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk
